### ISSUE TITLE
training dataset

### ISSUE THREAD

**Issue by kclim2** [SihamTabik/Pistol-Detection-in-Videos#1]
any chance you could also upload the training dataset for us to train our deep neural network?

**Comment by SihamTabik** [comment]
We'll upload the training dataset once our paper get published in a Journal. I hope  it  will be soon.

**Comment by breenmachine** [comment]
Any update on this? Would it be possible to get a copy of the training dataset?

**Comment by SihamTabik** [comment]
The review process  in the Journal is being slow. Once our paper gets accepted and published we will publish the dataset.

**Comment by curiouser001** [comment]
Hi, Did you publish the dataset? When you publish? Thank you.

**Comment by SasankYadati** [comment]
Is the dataset published? Please let me know. Thanks.

**Comment by RakeshChandran** [comment]
Hi.. Your paper looks great...Kindly share your training dataset at the earliest..

**Comment by SihamTabik** [comment]
Dear all, 

Thank you very much for your interest on our work. However, we are very sorry to inform you that we are not going to publish the training data in the near future since we are working on improving and extending it to more classes. Once we consider releasing it, I'll inform you through this thread.

Regards
Siham

**Comment by SasankYadati** [comment]
That's fine. I understand. Can you tell us the method you used to create the dataset?

**Comment by SihamTabik** [comment]
We have just released the first pistol-dataset.
For train:
https://www.dropbox.com/s/q23bb4xdp1pn69o/BK4.zip?dl=0
For test:
https://www.dropbox.com/s/opr8my5avr3zzfd/Testk.tar.gz?dl=0

If you use this dataset, please cite this paper :
Automatic Handgun Detection Alarm in Videos Using Deep Learning
R Olmos, S Tabik, F Herrera
Neurocomputing. DOI: https://doi.org/10.1016/j.neucom.2017.05.012.

**Comment by shadow111** [comment]
Hello,
please can you upload the data-set for training because the link seems not working!
Thank you

**Comment by oarriaga** [comment]
@SihamTabik the training dataset link is still broken. Would you provide the link in the near future?

**Comment by SihamTabik** [comment]
This link should work:
https://www.dropbox.com/s/ln18a6b7swlrcfc/BK4.zip?dl=0
Please, check that everything is ok.

Regards,
Siham

**Comment by SihamTabik** [comment]
By the way, this is an open link, fo 50 days, of our paper. 

https://authors.elsevier.com/a/1WFDB3INuk2l8a

**Comment by AVCarreiro** [comment]
Thank you @SihamTabik! 

Any chance you're also releasing Dataset 5, with the bounding boxes information? 

Best regards,

Andre

**Comment by SasankYadati** [comment]
I  have created guns dataset with bounding boxes. If you are interested, do take a look.
https://github.com/SasankYadati/Guns-Dataset

**Comment by SihamTabik** [comment]
Thank you SasankYadati for the dataset. I will have a closer look at it.

We released the two datasets used in the paper through this link:
http://sci2s.ugr.es/weapons-detection

Best regards,
Siham

**Comment by RakeshChandran** [comment]
Hi Siham,

Sorry, I missed the window on this one. Anyway, you would be able to share
this dataset again? This link seems like it is not active anymore.



Thanks and Regards,

Rakesh Chandran.N

**Comment by SihamTabik** [comment]
I've checked the link and it is working.
